@isTest
private class CongratulationsBoardControllerTest {
	@isTest
    private static void wrapperTest() {
        //Contact testContact = new Contact(Name = 'Jerry Small')
        
        /*    
        String nameOfAssociate = 'Jerry Small';
        String nameOfClient = 'Client 1';
        
        CongratulationsBoardController.AssociateClientWrapper testWrapper = new CongratulationsBoardController.AssociateClientWrapper(nameOfAssociate, nameOfClient);
        
        System.assertEquals('Jerry Small', testWrapper.associateName);
        System.assertEquals('Client 1', testWrapper.clientName);
        */
    }
}